# Generated by Django 4.2.7 on 2026-05-25 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel Data'), ('SAP_PROCUREMENT', 'SAP Procurement Data'), ('UTILITY_ELECTRICITY', 'Utility Electricity Data'), ('TRAVEL_FLIGHTS', 'Travel - Flights'), ('TRAVEL_HOTELS', 'Travel - Hotels'), ('TRAVEL_GROUND', 'Travel - Ground Transport')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawIngestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField()),
                ('parsing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_ingestions', to='core.datasource')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_ingestions', to='core.organization')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_row_id', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('SAP', 'SAP Data'), ('UTILITY', 'Utility Data'), ('TRAVEL', 'Travel Data')], max_length=20)),
                ('data', models.JSONField()),
                ('scope', models.IntegerField(blank=True, choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')], null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_normalized', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rows', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_rows', to='core.datasource')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_rows', to='core.organization')),
                ('raw_ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_rows', to='core.rawingestion')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.organization'),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('UNFLAGGED', 'Unflagged')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('normalized_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='core.normalizedrow')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='core.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='normalizedrow',
            index=models.Index(fields=['org', 'data_type', 'date'], name='core_normal_org_id_85c142_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrow',
            index=models.Index(fields=['org', 'flagged'], name='core_normal_org_id_dc8493_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrow',
            index=models.Index(fields=['approved_by'], name='core_normal_approve_e966ca_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['org', 'timestamp'], name='core_approv_org_id_6c7d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['normalized_row'], name='core_approv_normali_60ab70_idx'),
        ),
    ]
